[package]
name = "springboard"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.4"
fs_extra = "1.3.0"
inquire = "0.6.2"
project-root = "0.2.2"
